---
title: "Aviso de Privacidade e Uso de Dados da MelonMundi"
editor: visual
---

Atualizado em 06 de maio de 2024.

Nós agradecemos a você por escolher a MelonMundi e por nos confiar como parceiros na melhoria dos serviços oferecidos.

Queremos que você saiba, de forma clara e direta, a quais informações e dados nós temos acesso e o que fazemos com eles. Por isso, este Aviso de Privacidade foi elaborado. Recomendamos que você o leia com atenção e, caso tenha qualquer dúvida, fique à vontade para entrar em contato conosco, será um prazer lhe atender! Basta enviar um e-mail para **administrativo\@melonmundi.com** ou enviar uma mensagem para o WhatsApp da MelonMundi.

**1. Quem somos**

A MelonMundi está comprometida em proteger a sua privacidade e em cumprir com todas as leis e regulamentos aplicáveis, incluindo a Lei Geral de Proteção de Dados (LGPD, Lei nº 13.709/18). Esta Política de Privacidade descreve como coletamos, usamos, protegemos e compartilhamos suas informações pessoais quando você utiliza nosso site e as ferramentas fornecidas.

**2. Coleta de Informações**

Não coletamos intencionalmente informações pessoais identificáveis dos usuários deste site ou das ferramentas fornecidas, exceto quando fornecidas voluntariamente pelos usuários para utilizar as funcionalidades das ferramentas. As informações inseridas pelos usuários são coletadas apenas para o propósito específico de fornecer a funcionalidade das ferramentas e ajudar os usuários na tomada de decisões relacionadas à agricultura.

**3. Uso de Informações**

As informações inseridas pelos usuários nas ferramentas fornecidas são utilizadas exclusivamente para fornecer a funcionalidade das ferramentas e melhorar a experiência do usuário. Não utilizamos essas informações para qualquer outro propósito sem o consentimento expresso do usuário.

**4. Armazenamento e Segurança de Informações**

As informações inseridas pelos usuários nas ferramentas fornecidas não são armazenadas em nossos servidores ou em qualquer outro local. Elas são processadas apenas durante a sessão em que as ferramentas são utilizadas e são excluídas após o encerramento da sessão. Implementamos medidas de segurança adequadas para proteger as informações durante o uso das ferramentas.

**5. Uso de Navegação e Cookies**

Utilizamos cookies para melhorar a experiência do usuário e personalizar o conteúdo do site de acordo com as preferências do usuário. Cookies são pequenos arquivos de texto que são armazenados no dispositivo do usuário quando o site é acessado. Eles são usados para lembrar informações de sessão, como preferências de idioma, e para coletar informações sobre a interação do usuário com o site, como páginas visitadas e tempo gasto em cada página.

**6. Consentimento e Controle do Usuário**

Ao utilizar este site e as ferramentas fornecidas, você concorda com os termos desta Política de Privacidade e com o uso de cookies. Os usuários têm o direito de recusar ou desativar cookies em seus navegadores, no entanto, isso pode afetar a funcionalidade do site.

**7. Alterações na Política de Privacidade**

Esta Política de Privacidade pode ser atualizada periodicamente para refletir mudanças em nossas práticas de privacidade ou em conformidade com a legislação aplicável. Quaisquer alterações significativas serão destacadas neste site.

**8. Contato**

Se tiver alguma dúvida sobre esta Política de Privacidade ou sobre o uso de cookies, entre em contato conosco através do e-mail **administrativo\@melonmundi.com**.

Esta Política de Privacidade foi atualizada pela última vez em 06 de maio de 2024.
