---
title: "Termos e Condições de Uso"
---

**Termos e Condições de Uso**

Atualizado em 6 de maio de 2024.

Ao acessar e utilizar este website e as ferramentas fornecidas, você concorda com os seguintes termos e condições. Se você não concordar com estes termos, por favor, não utilize este site.

**1. Uso do Site e das Ferramentas**

1.1. Este site e as ferramentas fornecidas são destinados apenas para uso pessoal e não comercial. Você concorda em utilizá-los apenas para os fins previstos e de acordo com todas as leis e regulamentos aplicáveis.

1.2. Você concorda em não utilizar este site de forma que possa danificar, desabilitar, sobrecarregar ou prejudicar de qualquer forma a sua funcionalidade ou a funcionalidade das ferramentas fornecidas.

**2. Propriedade Intelectual**

2.1. Todo o conteúdo deste site, incluindo, mas não se limitando a textos, imagens, gráficos, logotipos e software, é de propriedade da MelonMundi ou de seus licenciadores e está protegido por leis de direitos autorais e outras leis de propriedade intelectual.

2.2. Você concorda em não copiar, reproduzir, distribuir, transmitir, exibir, vender, licenciar ou explorar de qualquer forma o conteúdo deste site sem a autorização prévia por escrito da MelonMundi.

**3. Responsabilidade**

3.1. Este site e as ferramentas fornecidas são fornecidos "como estão" e "conforme disponível", sem garantias de qualquer tipo, expressas ou implícitas. A MelonMundi não garante que este site será livre de erros ou que o acesso a ele será ininterrupto.

3.2. Em nenhuma circunstância a MelonMundi será responsável por quaisquer danos diretos, indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso ou da impossibilidade de uso deste site ou das ferramentas fornecidas.

**4. Links para Sites de Terceiros**

4.1. Este site pode conter links para sites de terceiros que não são controlados ou operados pela MelonMundi. A inclusão de qualquer link não implica em endosso por parte da MelonMundi e não somos responsáveis pelo conteúdo ou pela política de privacidade de tais sites.

**5. Alterações nos Termos e Condições**

5.1. A MelonMundi reserva-se o direito de atualizar ou modificar estes termos e condições a qualquer momento, sem aviso prévio. O uso continuado deste site após tais alterações constituirá a sua aceitação dessas alterações.

**6. Lei Aplicável**

6.1. Estes termos e condições serão regidos e interpretados de acordo com as leis do \[inserir país ou estado\], sem levar em consideração os princípios de conflitos de leis.

**7. Contato**

7.1. Se tiver alguma dúvida sobre estes termos e condições de uso, entre em contato conosco através do e-mail **administrativo\@melonmundi.com**.

Estes Termos e Condições de Uso foram atualizados pela última vez em 6 de maio de 2024.
